# inventory/00112233-4455-6677-8899-aabbccddeeff.yaml
key_id: 00112233-4455-6677-8899-aabbccddeeff
alias: db-encryption-dev
environment: dev
owner: db-admins@tecro
purpose: Encrypting sensitive columns in the development database
created_at: "2024-03-01T18:00:00Z"
rotation_interval_days: 730
location: "azure-key-vault://tecro-dev-vault.vault.azure.net/keys/db-dev-key"
compliance:
  pci_scope: none
  nist_classification: internal
tags: [database, encryption, dev]