# inventory/a1b2c3d4-e5f6-7890-1234-567890abcdef.yaml
key_id: a1b2c3d4-e5f6-7890-1234-567890abcdef
alias: internal-api-auth
environment: staging
owner: api-gateway-team@tecro
purpose: JWT signing for internal service-to-service communication
created_at: "2024-01-20T14:30:00Z"
rotation_interval_days: 365
location: "aws-kms://arn:aws:kms:us-east-1:123456789012:key/a1b2c3d4-e5f6-7890-1234-567890abcdef"
compliance:
  pci_scope: none
  nist_classification: confidential
tags: [jwt, auth, api-gateway, staging]