# inventory/a1b2c3d4-e5f6-7890-1234-567890abcdef.yaml
key_id: a1b2c3d4-e5f6-7890-1234-567890abcdef
alias: internal-api-auth
environment: staging
owner: api-gateway-team@tecro
purpose: JWT signing for internal service-to-service communication
created_at: "2024-01-20T14:30:00Z"
rotation_interval_days: 365
location: "aws-kms://arn:aws:kms:us-east-1:123456789012:key/a1b2c3d4-e5f6-7890-1234-567890abcdef"

compliance:
  pci_scope: none
  nist_classification: confidential
  sox_applicable: false
  gdpr_applicable: true
  retention_period_days: 2555

lifecycle:
  status: active
  created_by: api-gateway-team
  approved_by: key-inventory-admin
  approved_at: "2024-01-20T14:30:00Z"
  last_rotated_at: "2024-01-20T14:30:00Z"
  next_rotation_due: "2025-01-20T14:30:00Z"
  rotation_count: 0
  emergency_contact: security-team@tecro

technical:
  key_type: jwt
  key_size: 2048
  algorithm: RS256
  encoding: pkcs8
  key_store_type: aws-kms
  high_availability: true
  backup_location: "aws-kms://arn:aws:kms:us-west-2:123456789012:key/backup-a1b2c3d4"

relationships:
  depends_on: []
  used_by: ["api-gateway", "internal-services"]
  related_keys: []
  environments: ["staging"]

operational:
  monitoring_enabled: true
  alerting_enabled: true
  auto_rotation_enabled: true
  emergency_revocation_enabled: true
  cost_center: "CC-INFRA-001"
  project_code: "PROJ-API-2024"

audit:
  access_logs_enabled: true
  usage_tracking_enabled: true
  compliance_scan_enabled: true
  last_compliance_check: "2024-01-20T14:30:00Z"
  compliance_status: compliant

metadata:
  version: "2.0"
  documentation_url: "https://wiki.tecro.com/api-gateway/auth-keys"
  ticket_reference: "INFRA-1234"
  business_justification: "Required for secure internal service communication"
  risk_assessment: medium

tags: [jwt, auth, api-gateway, staging]

custom_fields:
  business_owner: "api-gateway-product@tecro"
  disaster_recovery_tier: "tier-2"
  encryption_at_rest: true