key_id: a3b4c5d6-e7f8-9a0b-1c2d-3e4f5a6b7c8d
alias: api-rate-limit-dev
environment: dev
owner: platform-team@tecro
purpose: API rate limiting token encryption
created_at: "2024-06-15T14:20:00Z"
rotation_interval_days: 90
location: "aws-kms://arn:aws:kms:us-east-1:123456789012:key/a3b4c5d6-e7f8-9a0b-1c2d-3e4f5a6b7c8d"
compliance:
  pci_scope: none
  nist_classification: internal
tags: [api, rate-limiting, dev, platform]