key_id: b6c7d8e9-f0a1-2b3c-4d5e-6f7a8b9c0d1e
alias: customer-pii-encryption-stage
environment: staging
owner: privacy-team@tecro
purpose: Customer PII data encryption for staging tests
created_at: "2024-05-25T09:45:00Z"
rotation_interval_days: 30
location: "hashicorp://privacy-kv/kv/data/customer/pii-encryption"
compliance:
  pci_scope: none
  nist_classification: secret
tags: [pii, encryption, privacy, staging]