key_id: b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e
alias: s3-encryption-prod
environment: prod
owner: storage-team@tecro
purpose: S3 bucket encryption for customer data
created_at: "2024-05-15T10:30:00Z"
rotation_interval_days: 365
location: "aws-kms://arn:aws:kms:us-west-2:123456789012:key/b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e"
compliance:
  pci_scope: cardholder-data
  nist_classification: secret
tags: [s3, encryption, storage, prod]