key_id: b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e
alias: s3-encryption-prod
environment: prod
owner: storage-team@tecro
purpose: S3 bucket encryption for customer data in production
created_at: "2024-05-15T10:30:00Z"
rotation_interval_days: 365
location: "aws-kms://arn:aws:kms:us-west-2:123456789012:key/b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e"

compliance:
  pci_scope: cardholder-data
  nist_classification: secret
  sox_applicable: true
  gdpr_applicable: true
  retention_period_days: 2555

lifecycle:
  status: active
  created_by: storage-team
  approved_by: key-inventory-admin
  approved_at: "2024-05-15T10:30:00Z"
  last_rotated_at: "2024-05-15T10:30:00Z"
  next_rotation_due: "2025-05-15T10:30:00Z"
  rotation_count: 0
  emergency_contact: security-team@tecro

technical:
  key_type: symmetric
  key_size: 256
  algorithm: AES-256-GCM
  encoding: base64
  key_store_type: aws-kms
  high_availability: true
  backup_location: "aws-kms://arn:aws:kms:us-east-1:123456789012:key/backup-b8c9d0e1"

relationships:
  depends_on: []
  used_by: ["s3-service", "data-pipeline", "backup-service"]
  related_keys: []
  environments: ["prod"]

operational:
  monitoring_enabled: true
  alerting_enabled: true
  auto_rotation_enabled: true
  emergency_revocation_enabled: true
  cost_center: "CC-STORAGE-001"
  project_code: "PROJ-STORAGE-2024"

audit:
  access_logs_enabled: true
  usage_tracking_enabled: true
  compliance_scan_enabled: true
  last_compliance_check: "2024-05-15T10:30:00Z"
  compliance_status: compliant

metadata:
  version: "2.0"
  documentation_url: "https://wiki.tecro.com/storage/s3-encryption"
  ticket_reference: "STORAGE-9753"
  business_justification: "PCI and GDPR compliant customer data encryption in S3"
  risk_assessment: critical

tags: [s3, encryption, storage, prod, pci, gdpr]

custom_fields:
  business_owner: "storage-product@tecro"
  disaster_recovery_tier: "tier-1"
  encryption_at_rest: true