key_id: c9d0e1f2-a3b4-5c6d-7e8f-9a0b1c2d3e4f
alias: file-storage-encryption-prod
environment: prod
owner: storage-team@tecro
purpose: File storage encryption for document management
created_at: "2024-04-05T13:15:00Z"
rotation_interval_days: 365
location: "azure-key-vault://tecro-prod-vault.vault.azure.net/keys/file-storage-key"
compliance:
  pci_scope: out-of-scope
  nist_classification: confidential
tags: [file-storage, encryption, documents, prod]