key_id: d2e3f4a5-b6c7-8d9e-0f1a-2b3c4d5e6f7a
alias: session-encryption-dev
environment: dev
owner: auth-team@tecro
purpose: User session data encryption for development
created_at: "2024-06-10T15:30:00Z"
rotation_interval_days: 60
location: "gcp-kms://projects/tecro-dev/locations/us-west1/keyRings/session-keys/cryptoKeys/session-dev"
compliance:
  pci_scope: none
  nist_classification: internal
tags: [session, encryption, auth, dev]