key_id: e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b
alias: reporting-encryption-stage
environment: staging
owner: analytics-team@tecro
purpose: Financial reporting data encryption for staging environment
created_at: "2024-03-22T07:00:00Z"
rotation_interval_days: 180
location: "aws-kms://arn:aws:kms:us-west-2:123456789012:key/e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"

compliance:
  pci_scope: none
  nist_classification: confidential
  sox_applicable: true
  gdpr_applicable: true
  retention_period_days: 2555

lifecycle:
  status: active
  created_by: analytics-team
  approved_by: key-inventory-admin
  approved_at: "2024-03-22T07:00:00Z"
  last_rotated_at: "2024-03-22T07:00:00Z"
  next_rotation_due: "2024-09-18T07:00:00Z"
  rotation_count: 0
  emergency_contact: analytics-team@tecro

technical:
  key_type: symmetric
  key_size: 256
  algorithm: AES-256-GCM
  encoding: base64
  key_store_type: aws-kms
  high_availability: true
  backup_location: "aws-kms://arn:aws:kms:us-east-1:123456789012:key/backup-e5f6a7b8"

relationships:
  depends_on: []
  used_by: ["reporting-service", "analytics-pipeline"]
  related_keys: []
  environments: ["staging"]

operational:
  monitoring_enabled: true
  alerting_enabled: true
  auto_rotation_enabled: true
  emergency_revocation_enabled: true
  cost_center: "CC-ANALYTICS-001"
  project_code: "PROJ-ANALYTICS-2024"

audit:
  access_logs_enabled: true
  usage_tracking_enabled: true
  compliance_scan_enabled: true
  last_compliance_check: "2024-03-22T07:00:00Z"
  compliance_status: compliant

metadata:
  version: "2.0"
  documentation_url: "https://wiki.tecro.com/analytics/reporting-encryption"
  ticket_reference: "ANALYTICS-7890"
  business_justification: "SOX-compliant financial reporting data protection"
  risk_assessment: high

tags: [reporting, encryption, analytics, staging, financial]

custom_fields:
  business_owner: "analytics-product@tecro"
  disaster_recovery_tier: "tier-2"
  encryption_at_rest: true