key_id: e7f8a9b0-c1d2-3e4f-5a6b-7c8d9e0f1a2b
alias: amex-tokenization-prod
environment: prod
owner: payments-platform@tecro
purpose: American Express card tokenization for payment processing
created_at: "2024-03-10T12:00:00Z"
rotation_interval_days: 60
location: "azure-key-vault://tecro-prod-vault.vault.azure.net/keys/amex-token-key"

compliance:
  pci_scope: cardholder-data
  nist_classification: top-secret
  sox_applicable: true
  gdpr_applicable: false
  retention_period_days: 2555

lifecycle:
  status: active
  created_by: payments-team
  approved_by: key-inventory-admin
  approved_at: "2024-03-10T12:00:00Z"
  last_rotated_at: "2024-03-10T12:00:00Z"
  next_rotation_due: "2024-05-09T12:00:00Z"
  rotation_count: 1
  emergency_contact: security-team@tecro

technical:
  key_type: symmetric
  key_size: 256
  algorithm: AES-256-GCM
  encoding: base64
  key_store_type: azure-kv
  high_availability: true
  backup_location: "azure-key-vault://tecro-backup-vault.vault.azure.net/keys/amex-token-backup"

relationships:
  depends_on: []
  used_by: ["payment-processor", "amex-gateway", "tokenization-service"]
  related_keys: ["42b7a3d1-f2e4-4a1b-8c8a-1234567890ab"]
  environments: ["prod"]

operational:
  monitoring_enabled: true
  alerting_enabled: true
  auto_rotation_enabled: true
  emergency_revocation_enabled: true
  cost_center: "CC-PAYMENTS-001"
  project_code: "PROJ-AMEX-2024"

audit:
  access_logs_enabled: true
  usage_tracking_enabled: true
  compliance_scan_enabled: true
  last_compliance_check: "2024-03-10T12:00:00Z"
  compliance_status: compliant

metadata:
  version: "2.0"
  documentation_url: "https://wiki.tecro.com/payments/amex-tokenization"
  ticket_reference: "PAY-3691"
  business_justification: "PCI-compliant American Express card tokenization"
  risk_assessment: critical

tags: [amex, tokenization, pci, prod, american-express]

custom_fields:
  business_owner: "payments-product@tecro"
  disaster_recovery_tier: "tier-1"
  encryption_at_rest: true